<?xml version='1.0' encoding='utf-8'?>
	<!DOCTYPE TesterList [
		<!ELEMENT TesterList (Tester)*>
		<!ELEMENT Tester (ClassName, Description, TestsListRif)>
		<!ATTLIST Tester 
		    name     CDATA    #REQUIRED
		    skip     CDATA    #REQUIRED
		>
		<!ELEMENT ClassName (#PCDATA)>
		<!ELEMENT Description (#PCDATA)>
		<!ELEMENT TestsListRif (#PCDATA)>
	]>
	<TesterList> 
		<Tester name="ParallelPriorityBehaviour" skip="false">
			<ClassName>test.parallelprioritybehaviour.ParallelPriorityBehaviourTesterAgent</ClassName>
			<Description> This item includes tests related to parallel priority behaviour.</Description>
			<TestsListRif>test/parallelprioritybehaviour/parallelPriorityBehaviourTestsList.xml</TestsListRif>
		</Tester>
	</TesterList>
